spacemeshos/svm

Cargo.lock
crates/svm-runtime-c-api/.gitignore
crates/svm-runtime-c-api/Cargo.toml
crates/svm-runtime-c-api/build.rs
crates/svm-runtime-c-api/examples/svm_wasmer.h

auto generate svm_wasmer.h

---

crates/svm-runtime-c-api/build.rs

ouputs header in target , added comments

---

apps/src/wallet/src/auth.rs
apps/src/wallet/src/imports.rs
apps/src/wallet/src/lib.rs
apps/src/wallet/src/write.rs

minor english edits as I go through code

minor comments edits (WIP)

---

crates/svm-app/src/traits/env.rs
crates/svm-app/tests/deploy_template_tests.rs
crates/svm-app/tests/exec_app_tests.rs
crates/svm-app/tests/spawn_app_tests.rs

As part of the validation of the raw transactions, we need to ensure there is no excessive payload.

Validate raw transaction has no extra payload

---

crates/svm-runtime-c-api/src/api.rs

Quick fix since the new storage module isn't used yet.

Fix v0.2 encode template error

---

.github/workflows/rust.yml

Trying to make the CI on Windows output a `.dll` artifact.

Windows CI should output a dll artifact

---

crates/svm-runtime/tests/vmcalls_tests.rs

forgot to uncomment assertion in the code

forgot to uncomment assertion.

---

Cargo.lock
crates/svm-runtime/src/import.rs

updating to wasmer `1.0.0-alpha4`

wasmer version bump `1.0.0-alpha4`

---

crates/svm-sdk/src/lib.rs

Fix for a broken doc-test under `svm-sdk`

svm-sdk - doc-test fix.

---

Cargo.lock
Cargo.toml
crates/compiler/Cargo.toml
crates/compiler/src/compiler.rs
crates/runtime/Cargo.toml

Wasmer version bump to `2.0.0-rc1`

Wasmer update

---

crates/runtime/src/env/mod.rs
crates/runtime/src/runtime/default.rs
crates/runtime/src/testing.rs

Naive template memoization

---

Cargo.lock
crates/cli/Cargo.toml
crates/cli/examples/call.json
crates/cli/examples/deploy.json
crates/cli/examples/spawn.json
crates/cli/src/clap_app.rs
crates/cli/src/main.rs
crates/cli/src/subcmd_tx.rs
crates/cli/src/subcmd_validate.rs
crates/codec/Cargo.toml

Closes https://github.com/spacemeshos/svm/issues/302. See also https://github.com/spacemeshos/svm/issues/301.

`svm-cli` `Transaction` crafting: `spawn`

---

crates/runtime-ffi/src/api.rs

Catch panics within critical FFI calls

---

crates/runtime/tests/wasm/log.wast
crates/sdk/std/src/log.rs
crates/sdk/std/src/string/mod.rs
crates/sdk/types/Cargo.toml

A few leftovers from the SVM SDK PR #335 
Closes #337

A few leftovers from the SVM SDK PR

---

LICENSE
crates/cli/src/main.rs
crates/hash/src/lib.rs
src/lib.rs

As per title. A good first step towards closing #290.

Small documentation improvements

---

.github/workflows/ci.yml
Cargo.lock
crates/cli/Cargo.toml

As per title; required for https://github.com/spacemeshos/go-svm integration.

Expose CLI builds as GitHub Actions artifactts

---

crates/runtime-ffi/src/api.rs

Add `no_mangle` to `svm_init`

---

docs/intro.md

I am starting to document SVM at a high level.
This PR is the first one, and it contains an introduction to SVM.

SVM High-level documentation - Introduction to SVM

---

docs/crates.md
docs/intro.md

High-level review of SVM crates.

Crates high-level review

---

.github/workflows/ci.yml
.guppy/hakari.toml
Cargo.lock
crates/runtime-ffi/Cargo.toml
crates/runtime/Cargo.toml
crates/runtime/src/wasm_store.rs
crates/sdk/MyTemplate-meta.json
crates/svm-workspace-hack/Cargo.toml
crates/svm/Cargo.toml

Singlepass on Windows!
@avive FYI

Wasmer update to v2.1.0 

---

crates/codec/src/receipt/call.rs
crates/codec/src/receipt/spawn.rs

Additional testing for Touched-Accounts and update codec documentation

---

.github/copy-artifacts.sh
.github/workflows/ci.yml

Provide builds for Apple Silicon
