spacemeshos/svm

- scripts/ci.sh
I just realise travis cache older build, that create more artifacts that we need.
> Removing older build, we don't want to keep them.

- crates/svm-common/src/address.rs
- crates/svm-common/src/helpers.rs
- crates/svm-common/src/macros.rs
- crates/svm-kv/tests/memory_kv_tests.rs
- crates/svm-runtime-c-api/src/receipt.rs
- crates/svm-runtime-c-api/tests/api_tests.rs
- crates/svm-runtime/tests/runtime.rs
- crates/svm-runtime/tests/vmcalls.rs
- crates/svm-storage/src/default/page_hasher.rs
- crates/svm-storage/src/default/state_hasher.rs
- crates/svm-storage/src/testing/app_page_cache.rs
- crates/svm-storage/src/testing/app_pages.rs
- crates/svm-storage/src/testing/app_storage.rs
- crates/svm-storage/src/testing/page.rs
- crates/svm-storage/tests/app_page_cache_tests.rs
- crates/svm-storage/tests/app_pages_tests.rs
- crates/svm-storage/tests/app_storage_tests.rs
Adding a helper method `Address::from(&str)` will make the tests look more intuitive.
We can then be have in our tests this:
```
let author = Address::from("@author");
let sender = Address::from("@sender");
```
> Generate friendly `Address` from String

- crates/svm-runtime/src/runtime/default.rs
- crates/svm-runtime/src/traits.rs
- crates/svm-runtime/tests/runtime.rs
The motivation for this PR is to add a `dry run` mode for a runtime.
Running in a dry mode is required when we want to simulate the execution of an app without modifying its state. A good use-case is when the Host would like to expose an app's data to the outside world.
> Adding `dry_run` flag mode.

- crates/svm-runtime-c-api/build.rs
- examples/c/Makefile
- examples/c/build.sh
- examples/c/counter.c
- examples/c/deploy_bytes.h
- examples/c/exec_app_bytes.h
- examples/c/func_args.h
- examples/c/func_buf.h
- examples/c/host_ctx.h
- examples/c/receipt.h
Since the `examples` directory has been moved from within `svm-runtime-c-api/src/examples` to the project root dir, we have to fix the copy of `svm.h` file and and `build.sh` (which grabs the `svm` objectfile). 
It's a prerequisite to #79
> Fixing copying `svm` header & objectfile

- crates/svm-runtime-c-api/build.rs
- examples/c/build.sh
* Rust build script to output `svm.h` into `svm/target/release` instead of `svm/target/debug/build/svm-runtime-c-api-X/out`
* `build.sh` to copy objectfile instead of moving
* `build.sh` to copy `svm.h`, created by the Rust build script
> Refactor build scripts

- crates/svm-app/src/rocksdb/app_store.rs
- crates/svm-app/src/rocksdb/template_store.rs
- crates/svm-kv/src/rocksdb/db.rs
- crates/svm-runtime-c-api/src/api.rs
- crates/svm-runtime-c-api/src/error.rs
- crates/svm-runtime-c-api/src/import.rs
- crates/svm-runtime-c-api/src/lib.rs
- crates/svm-runtime-c-api/src/testing/mod.rs
- crates/svm-runtime-c-api/tests/api_tests.rs
- crates/svm-runtime-c-api/tests/wasm/update-balance.wast
- crates/svm-runtime/src/runtime/default.rs
- crates/svm-runtime/src/runtime/rocksdb.rs
- crates/svm-runtime/src/settings.rs
- crates/svm-runtime/src/testing.rs
- crates/svm-runtime/tests/runtime.rs
The current C-API returns `svm_result_t`, we'd like to return also the reason (as `svm_byte_array`)
for the errors.
> Returning `error` via the c-api

- Cargo.lock
- Cargo.toml
- crates/svm-app/Cargo.toml
- crates/svm-app/src/rocksdb/template_store.rs
- crates/svm-kv/src/key.rs
- crates/svm-kv/src/lib.rs
- crates/svm-kv/src/memory.rs
- crates/svm-kv/src/rocksdb/db.rs
- crates/svm-kv/src/traits.rs
- crates/svm-kv/tests/asserts.rs
- crates/svm-kv/tests/memory_kv_tests.rs
- crates/svm-runtime-c-api/src/receipt/exec_app.rs
- crates/svm-runtime-c-api/src/receipt/spawn_app.rs
- crates/svm-runtime/src/runtime/rocksdb.rs
- crates/svm-runtime/src/testing.rs
- crates/svm-storage/Cargo.toml
- crates/svm-storage/src/app_pages.rs
- crates/svm-storage/src/default/page_hasher.rs
- crates/svm-storage/src/default/state_hasher.rs
- crates/svm-storage/src/lib.rs
- crates/svm-storage/src/page/joined_pages_hash.rs
- crates/svm-storage/src/testing/app_page_cache.rs
- crates/svm-storage/src/testing/app_pages.rs
- crates/svm-storage/src/testing/app_storage.rs
- crates/svm-storage/src/testing/page.rs
- crates/svm-storage/src/traits.rs
- crates/svm-storage/tests/app_page_cache_tests.rs
- crates/svm-storage/tests/app_pages_tests.rs
- crates/svm-storage/tests/app_storage_tests.rs
- crates/svm-storage/tests/asserts.rs
Adding logical isolation to the keys stored under SVM.
Each key will have a namespace prefix and a `:` separator.
In case an empty namespace is used for a key then no `:` separator will be used.
Examples:
* Keys for app-state will be `st` (usage: `st:A19F...`)
* Keys of app-pages data will be `p`  (usage: `p:A19F...`)
* Keys of templates will be `t`   (usage: `t:A19F...`)
> Introducing `namespace` to the kv-store API.

- crates/svm-runtime-c-api/src/api.rs
- crates/svm-runtime-c-api/src/lib.rs
- crates/svm-runtime-c-api/src/receipt/exec_app.rs
- crates/svm-runtime-c-api/src/receipt/spawn_app.rs
- crates/svm-runtime-c-api/src/testing/receipt/exec_app.rs
- crates/svm-runtime-c-api/src/testing/receipt/helpers.rs
- crates/svm-runtime-c-api/src/testing/receipt/spawn_app.rs
- crates/svm-runtime-c-api/src/value.rs
Adding Receipt helper for extracting the spawned-app `ctor_returns` and executed-app `func_returns`.
> Receipt helper for extracting `returns`

- crates/svm-runtime-c-api/src/api.rs
- crates/svm-runtime-c-api/src/lib.rs
- crates/svm-runtime-c-api/src/receipt/exec_app.rs
- crates/svm-runtime-c-api/src/receipt/spawn_app.rs
- crates/svm-runtime-c-api/src/testing/receipt/exec_app.rs
- crates/svm-runtime-c-api/src/testing/receipt/helpers.rs
- crates/svm-runtime-c-api/src/testing/receipt/spawn_app.rs
- crates/svm-runtime-c-api/src/value.rs
- crates/svm-runtime-c-api/tests/api_tests.rs
- crates/svm-runtime/src/runtime/default.rs
- crates/svm-runtime/src/runtime/runtime.rs
The original motivation we had `dry_run` flag was for enforcing non-changing state mode.
This turned to be a half-backed feature and it's actually not really a necessary one.
> Remove dry run flag

- apps/src/wallet/Cargo.toml
- apps/src/wallet/build.sh
The compiler must produce a dynamic system library (`cdylib`).
> Fix multisig wallet WASM build

- Cargo.lock
- crates/svm-runtime-c-api/src/api.rs
- crates/svm-runtime-c-api/src/helpers.rs
- crates/svm-runtime-c-api/src/import.rs
- crates/svm-runtime-c-api/src/lib.rs
- crates/svm-runtime-c-api/src/wasmer.rs
- crates/svm-runtime/src/runtime/default.rs
- crates/svm-runtime/tests/vmcalls.rs
We want the SVM import function struct to hold `Vec<WasmType>` and not `svm_byte_array`.
(within the `svm-runtime-c-api` crate).
By having the requested, the `go-svm` (or future similar clients) can pass the function signature's
`params` and `returns` and reclaim their memory right after. That will work since Rust will convert that data internally to a new `Vec<WasmType>` isolated from the raw input.
https://github.com/spacemeshos/svm/blob/2ef6696cd5ee0c1d5195af3d6c8f91fd559d6a11/crates/svm-runtime-c-api/src/api.rs#L239
> Import func sig clones data

- Cargo.lock
- Cargo.toml
- crates/svm-app/Cargo.toml
- crates/svm-app/src/raw/template/serialize.rs
- crates/svm-app/src/raw/template/wire.rs
- crates/svm-app/src/testing/template_builder.rs
- crates/svm-app/src/types/template.rs
- crates/svm-cli/Cargo.toml
- crates/svm-cli/src/app_template.rs
- crates/svm-layout/Cargo.toml
- crates/svm-layout/src/builder.rs
- crates/svm-layout/src/layout.rs
- crates/svm-layout/src/lib.rs
- crates/svm-runtime-c-api/Cargo.toml
- crates/svm-runtime-c-api/src/api.rs
- crates/svm-runtime-c-api/src/layout.rs
- crates/svm-runtime-c-api/src/lib.rs
- crates/svm-runtime-c-api/tests/api_tests.rs
- crates/svm-runtime/Cargo.toml
- crates/svm-runtime/src/settings.rs
- crates/svm-runtime/src/testing.rs
- crates/svm-runtime/src/vmcalls/storage2.rs
- crates/svm-runtime/tests/runtime.rs
- crates/svm-runtime/tests/vmcalls.rs
- crates/svm-runtime/tests/vmcalls2.rs
- crates/svm-storage2/src/app/mod.rs
- crates/svm-storage2/src/layout/mod.rs
- crates/svm-storage2/src/lib.rs
When building a [`template` transaction][build] using `svm_encode_app_template` the `DataLayout` is should be given `svm_byte_array`.
We need to parse it into `DataLayout`
[build]: https://github.com/spacemeshos/svm/blob/1424617fde68a27effbf4c41bc407b219174b9ce/crates/svm-runtime-c-api/src/api.rs#L1261
> `svm_byte_array` to `DataLayout`

- crates/svm-runtime/src/testing.rs
- crates/svm-storage2/src/app/kv.rs
- crates/svm-storage2/src/app/mod.rs
- crates/svm-storage2/src/app/raw.rs
- crates/svm-storage2/src/lib.rs
- crates/svm-storage2/src/testing.rs
- crates/svm-storage2/tests/app_storage_tests.rs
After calling `commit` on an `AppStorage` instance, the executed application's `State` is being changed. We need to be able to propagate the new `State` back to the `AppStorage`.
This is required so that an executing `Runtime` can return in the `Receipt`(s) the new `State` of the application.
> Making `AppStorage` `State`-aware 

- crates/svm-runtime/src/vmcalls/storage.rs
- crates/svm-runtime/tests/runtime_tests.rs
- crates/svm-runtime/tests/vmcalls_tests.rs
- crates/svm-storage/src/app/mod.rs
Since WASM's Memory is laying out integers in Little-Endian order we need to adapt the storage vmcalls `getXXX/setXXX` to be Little-Endian too.
Currently, these vmcalls are storing integers in Big-Endian order and that could cause issues when using the `get160/set160` and `get256/set256` vmcalls.
After moving to use wasmer with the `cranelift` compiler (which support wasm muti-return values) we could make the `get160/set160` and `get256/set256` functional.
Then we could add tests the simulate sending `Address` and `PubKey` via the `function buffer`.
> `getXXX/setXXX` store each int in Little-Endian format

- Cargo.lock
- Cargo.toml
- crates/svm-compiler/Cargo.toml
- crates/svm-compiler/src/compiler.rs
- crates/svm-compiler/src/lib.rs
- crates/svm-runtime-c-api/Cargo.toml
- crates/svm-runtime/Cargo.toml
- crates/svm-runtime/src/helpers/gas.rs
- crates/svm-runtime/tests/runtime_tests.rs
This PR substitutes the used wasmer compiler to `cranelift`. (it has Windows support).
It means that the gas-metering functionality won't work for now. 
Fortunately, this should be supported in wasmer soon.
> Temporarily substituting wasmer's `singlepass compiler` for `cranelift`

- .github/workflows/rust.yml
The new wasmer requires `automake` which seems to be missing from the default macOS image of GitHub Actions.
> macOS: brew install automake

- crates/svm-codec/examples/test.js
Adapt the `svm-codec` js tests to expect a string for as a function identifier.
> Adapt the svm-codec js tests

- crates/svm-codec/src/app/mod.rs
- crates/svm-codec/src/receipt/deploy_template.rs
- crates/svm-codec/src/receipt/exec_app.rs
- crates/svm-codec/src/receipt/spawn_app.rs
- crates/svm-codec/src/template/mod.rs
- crates/svm-codec/src/transaction/mod.rs
- crates/svm-runtime-c-api/src/api.rs
- crates/svm-runtime-c-api/src/byte_array.rs
- crates/svm-runtime-c-api/src/macros.rs
- crates/svm-runtime-c-api/src/types.rs
- crates/svm-runtime-c-api/src/value.rs
- crates/svm-runtime-c-api/tests/api_tests.rs
Added `capacity` to `svm_byte_array` (the total number of allocated bytes).
It may be unequal and bigger than `length` if the `svm_byte_array` instance is an alias to an instance of a data structure such as `Vec` (which in order to properly get deallocated needs first to be re-constructed using the proper allocated capacity).
[Vec#leak](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.leak) wasn't used because in order to remove the surplus capacity it clones the data, while `svm_byte_array` is intended to be an alias. 
Closing https://github.com/spacemeshos/svm/issues/129.
> add `capacity` to `svm_byte_array`

- crates/svm-runtime-c-api/src/api.rs
- crates/svm-runtime-c-api/tests/api_tests.rs
- crates/svm-runtime/src/context.rs
- crates/svm-runtime/src/runtime/default.rs
- crates/svm-runtime/src/runtime/rocksdb.rs
- crates/svm-runtime/src/testing.rs
- crates/svm-runtime/tests/runtime_tests.rs
- crates/svm-runtime/tests/vmcalls_tests.rs
Removed `host` raw pointer from the runtime context, which is no longer intended to be passed to the host import function.
> Remove `host` raw pointer from the runtime context

- crates/svm-runtime-c-api/src/api.rs
The missing field is causing a panic. 
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates/svm-codec/src/api/builder/app_builder.rs:89:30
```
> `svm_encode_spawn_app` to support `name`

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- crates/svm-compiler/Cargo.toml
- crates/svm-compiler/src/compiler.rs
- crates/svm-kv/Cargo.toml
- crates/svm-kv/src/lib.rs
- crates/svm-runtime-c-api/Cargo.toml
- crates/svm-runtime-c-api/src/api.rs
- crates/svm-runtime-c-api/src/lib.rs
- crates/svm-runtime/Cargo.toml
- crates/svm-runtime/src/env/mod.rs
- crates/svm-runtime/src/lib.rs
- crates/svm-runtime/src/runtime/mod.rs
- crates/svm-storage/Cargo.toml
Compiling `rocksdb` takes a significant amount of time.
We can boost the compilation time by adding features flags that will use for development purposes only 
in-memory key-value store.
> using feature flags for faster compilation.

- crates/svm-codec/src/api/json/calldata.rs
- crates/svm-ffi/src/byte_array.rs
`Calldata` encoding to remove `nargs`, since it's not really needed and causing some discrepancies in the codec.
> Calldata encoding to remove nargs

- crates/svm-runtime-c-api/src/api.rs
`svm_ffi_state_kv_create` is currently creating the KV as a concrete type (`Rc<RefCell<ExternKV>>`) before allocating it on the heap.
When the pointer is later used in `svm_memory_runtime_create`, the unsafe dereference type inference is to a trait object (`Rc<RefCell<dyn StatefulKV>>`). It makes all methods calls on the dereferenced value to cause segmentation faults. 
This issue was reproduced by the Go client. I don't think it has test coverage in this repo.
> Fix FFI-state-KV allocation

- crates/svm-runtime-c-api/src/api.rs
- crates/svm-storage/src/kv/ffi.rs
- crates/svm-storage/src/kv/mock/ffi.rs
When using FFI key-value store for managing apps' `State` it's up to the host to manage that.
This PR adds a missing piece that demands the host to reply with its most recent `State` (a.k.a the `HEAD`) when asked for.
We could have managed without this method since after we already use `checkpoint` which returns back the new `State`.
However, in order to KISS and be fully compliant with the `StatefulKV` trait - we`d be better having an explicit `head` FFI function as well.
Also, this SMIP has been updated:
https://github.com/spacemeshos/SMIPS/issues/20
> `ExternKV` requires FFI-pointer to `head` as well.

- rust-toolchain.toml
Recent `rustup` versions (>= 1.23) gained the ability to automatically select Rust toolchain components based on a TOML configuration file. This simplifies IDE interaction, editor and `rust-analyzer` support.
> Add a Rust toolchain file which defaults to nightly

- crates/runtime/Cargo.toml
- crates/runtime/src/context.rs
- crates/runtime/src/env/memory/app_store.rs
- crates/runtime/src/env/mod.rs
- crates/runtime/src/env/traits/store.rs
- crates/runtime/src/error/mod.rs
- crates/runtime/src/lib.rs
- crates/runtime/src/runtime/config.rs
- crates/runtime/src/runtime/default.rs
- crates/runtime/src/testing.rs
- crates/runtime/src/vmcalls/mod.rs
- crates/runtime/tests/vmcalls_tests.rs
The executed SVM-flavored Wasm has imports of `function` kind. 
New kinds of imports (such as `Memory/Table/Global`) are not expected to be used in the foreseeable future.
The functions imports are grouped into: 
These host functions deal primarily with managing the `Account` storage.
The internals are SVM specific and are Node-agnostic.
The internals will be clustered under the `svm` namespace.
Here we can inject upon Runtime initialization a  functionality that is Node-aware.
It will include features such as:
* `get_balance` - asking for the current executed Account balance
* `transfer` - sending coins from the current Account to another Account
The externals will be clustered under the `sm` namespace.
This design should make it easier for other Blockchains to integrate with SVM.
The …
> Only native host functions

- crates/storage/tests/account_storage_tests.rs
As per title. Closes https://github.com/spacemeshos/svm/issues/291.
Which one do you @YaronWittenstein prefer? With macros or functions? It seems more readable to me, but it's such a small change that reverting it back is perfectly fine for me.
> Replace macros with functions within svm-storage

- crates/codec/src/section/preview.rs
- crates/runtime/src/func_env.rs
- crates/runtime/src/runtime/call.rs
- crates/runtime/src/runtime/default.rs
- crates/runtime/src/runtime/failure.rs
- crates/runtime/src/runtime/mod.rs
- crates/runtime/src/vmcalls/alloc.rs
- crates/runtime/src/vmcalls/calldata.rs
- crates/runtime/src/vmcalls/logs.rs
- crates/runtime/src/vmcalls/storage.rs
- crates/runtime/tests/vmcalls_tests.rs
- crates/types/src/transaction/context.rs
- crates/types/src/transaction/envelope.rs
This PR implements injection of both the `Envelope` and `Context` into the `FuncEnv`.
This is a preparation work for adding future host functions that will expose more information.
As an example, an executed transaction can ask for it's `Id` (the `transaction id` sits under the `Context`).
> svm-runtime: Injecting the `Envelope` and `Context` into `FuncEnv`

- crates/runtime/src/func_env.rs
- crates/runtime/src/testing.rs
- crates/storage/src/account/kv.rs
- crates/storage/src/testing.rs
Before this PR, `FuncEnv` implemented `Sync` and `Send` in an unsafe and potentially UB-prone manner. While SVM indeed is single-threaded, we can't guarantee that `wasmer` will not pass around items between threads (which they might even do unwittingly via `async` / `await`). We can't guarantee that `wasmer` is single-threaded as well, and we shouldn't, given that `WasmerEnv` requires `Sync + Send`.
This PR replaces some `Rc<RefCell<...>>` patterns with `Arc<Mutex<...>>` and `Arc<RwLock<...>>`. See https://github.com/spacemeshos/svm/issues/260.
> Replace `Runtime` locking mechanisms with thread-safe alternatives

- crates/codec/src/error.rs
This simplifies [`Display`](https://doc.rust-lang.org/std/fmt/trait.Display.html) logic for `svm_codec::ParseError` via `thiserror` and derives the implementation of `Debug`.
> Adopt `thiserror` for `ParseError` and `#[derive(Debug)]`

- crates/codec/src/call.rs
- crates/codec/src/spawn.rs
Some encoding-related helper functions in `svm_codec` are, in my opinion, way too small to justify the mental overhead. Let's remove them and inline their contents. Decoding-related helper functions encapsulate significant amounts of logic and thus are fine.
> Inline contents of some helper functions in `svm_codec`

- crates/codec/src/lib.rs
At the moment, we only compile WASM FFI functions when compiling to `wasm32-unknown-unknown`. This distinction between compilation targets, however, is not necessary and diminishes the amount of compiler help that we get when compiling to other targets. Let's make sure that those APIs are always present in the code and reduce target fragmentation.
> Always compile WASM APIs in `svm_codec`

- crates/runtime-ffi/src/api.rs
- crates/runtime-ffi/src/byte_array.rs
- crates/runtime-ffi/src/lib.rs
- crates/runtime-ffi/src/ref.rs
- crates/runtime-ffi/tests/api_tests.rs
See #260.
- Use `#![deny(unsafe_op_in_unsafe_fn)]`, which makes auditing `unsafe` code much easier.
- Use method-based casting on raw pointers rather than `as`. Behavior is better documented and they protect against `NULL` deference.
- Try to push `unsafe` code as high as possible within function bodies to highlight what `unsafe` operations we do.
- Cast pointers to reference as early as possible as they are the main cause of `unsafe`.
> Safer C APIs

- .github/workflows/ci.yml
- crates/abi/decoder/src/lib.rs
- crates/abi/encoder/src/lib.rs
- crates/abi/layout/src/lib.rs
- crates/cli/src/main.rs
- crates/codec/src/lib.rs
- crates/gas/src/lib.rs
- crates/hash/src/lib.rs
- crates/kv/src/lib.rs
- crates/layout/src/lib.rs
- crates/program/src/lib.rs
- crates/query/src/lib.rs
- crates/runtime-ffi/src/api.rs
- crates/runtime-ffi/src/lib.rs
- crates/runtime/src/lib.rs
- crates/sdk/alloc/src/lib.rs
- crates/sdk/host/src/lib.rs
- crates/sdk/macros/src/lib.rs
- crates/sdk/std/src/lib.rs
- crates/sdk/std/src/option.rs
- crates/sdk/std/src/string/mod.rs
- crates/sdk/std/src/vec.rs
- crates/sdk/storage/src/lib.rs
- crates/state/src/lib.rs
- crates/storage/src/lib.rs
- crates/types/src/lib.rs
As per title. This is also checked by CI, which ensures that we can always build documentation for `master`.
> Disallow broken intra-doc Cargo links

- .github/workflows/ci.yml
Workaround for https://github.com/rust-lang/rust/issues/50007.
> Only compile svm-runtime-ffi in CI

- Cargo.lock
- crates/state/Cargo.toml
Closes #365 . The latest Global State -related PRs have successfully isolated the usage of `async/await` within `svm_state::Storage`, which effectively removes the previous cause of this bug.
> Replace all usage of Actix with Tokio

- crates/abi-decoder/src/decoder.rs
- crates/abi-encoder/src/types/address.rs
- crates/abi-encoder/src/types/boolean.rs
- crates/abi-encoder/src/types/numeric.rs
- crates/abi-encoder/src/types/option.rs
- crates/abi-encoder/src/types/unit.rs
- crates/abi-layout/src/lib.rs
As per title. I think it's there for historical reasons, but now it's just nested hierarchy for no reasons.
> Remove the `svm_abi_layout::layout` module

- crates/codec/src/codec.rs
- crates/types/src/transaction/envelope.rs
The `Envelope` will also have an explicit `nonce` field.
It will be encoded via the FFI layer (will be called from `go-svm`)
> Added the `nonce` field to the `Envelope`

- crates/codec/src/api/json/mod.rs
- crates/codec/src/api/json/receipt.rs
- crates/codec/src/receipt/call.rs
- crates/codec/src/receipt/mod.rs
- crates/codec/src/receipt/spawn.rs
- crates/codec/src/receipt/touched_accounts.rs
- crates/runtime/src/func_env.rs
- crates/runtime/src/lib.rs
- crates/runtime/src/runtime/function.rs
- crates/runtime/src/runtime/mod.rs
- crates/runtime/src/runtime/runtime.rs
- crates/runtime/src/vmcalls/transfer.rs
- crates/runtime/tests/runtime_tests.rs
- crates/state/src/account_storage.rs
- crates/types/src/receipt/call.rs
- crates/types/src/receipt/spawn.rs
Closes https://github.com/spacemeshos/svm/issues/375.
This PR adds a `touched_accounts` field to both `SpawnReceipt` and `CallReceipt`. This is a set of account addresses that includes the following:
- Principal account address.
- Newly spawned account address (only for `spawn`).
- Any other address involved in a coin transfer during smart contract execution.
> Touched accounts

- crates/codec/src/api/json/receipt.rs
- crates/codec/src/receipt/error.rs
- crates/runtime-ffi/src/api.rs
- crates/runtime-ffi/tests/api_tests.rs
- crates/runtime/src/func_env.rs
- crates/runtime/src/lib.rs
- crates/runtime/src/price_registry.rs
- crates/runtime/src/runtime/call.rs
- crates/runtime/src/runtime/gas_tank.rs
- crates/runtime/src/runtime/mod.rs
- crates/runtime/src/runtime/price_cache.rs
- crates/runtime/src/runtime/runtime.rs
- crates/runtime/src/testing.rs
- crates/runtime/src/vmcalls/mod.rs
- crates/runtime/tests/runtime_tests.rs
- crates/runtime/tests/vmcalls_tests.rs
- crates/state/src/account_storage.rs
- crates/types/src/error.rs
- crates/types/src/template/mod.rs
- crates/types/src/template/section.rs
I want to refactor the `Runtime` of SVM.
Here are the changes done on this one:
The `FuncNotAllowed` requires a `target`.
Since we don't really have a `target` when spawning, I've ended up the `FuncNotCtor`
Initially, the `Runtime` expected external imports.
Back then, we thought that `Global-State`-related host functions would be implemented within the `go-spacemesh`.
Since then, the `Global State` has been moved to the Rust land, so we ended up with having setting empty `imports` as a parameter when initializing the `Runtime`
I created `TemplatePriceCache` to act as the cache for the `Template Pricing`. 
The `Runtime` expects now that cache as a dependency upon initialization. 
In practice, it'd be ideal to have only a single cache used throughout the process lifetime.
I thought it …
> Runtime refactoring

- .github/copy-artifacts.sh
- .github/workflows/ci.yml
Separates `x86_64` and `aarch64` release asset files for macOS.
> Separate macOS asset files by arch
